package com.master.core.constants;

public abstract class Constants {

    public static final class QrConstants {

        public static final String INVALID_QR = "INVALID_QR";
        public static final String MCC_CODE = "MCC_CODE";
        public static final String MERCHANT_NAME = "MERCHANT_NAME_QR";
        public static final String BANK_ACCOUNT_NAME = "BANK_ACCOUNT_NAME";
        public static final String DYNAMIC_QR = "DYNAMIC_QR";
        public static final String DB = "DATABASE";
        public static final String VALID_HSP = "VALID_HSP";
        public static final String INVALID_HSP = "INVALID_HSP";
        public static final String VERIFIED = "VERIFIED";
        public static final String PENDING = "PENDING";
    }

    public static final Long OTHER_HOSPITALS = (long) 4;
    public static final Long PARTNER_HOSPITALS = (long) 1;

    public static final String[] HSP_KEYWORDS = {
            "vascular surgery",
            "vascular medicine",
            "urology",
            "sports medicine",
            "radiology",
            "radiation oncology",
            "pulmonology",
            "public health",
            "psychiatry",
            "plastic, reconstructive and aesthetic surgery",
            "physical medicine and rehabilitation",
            "pathology",
            "paediatrics",
            "paediatric surgery",
            "paediatric rheumatology",
            "paediatric respiratory medicine",
            "paediatric nephrology",
            "paediatric infectious diseases",
            "paediatric haematology and oncology",
            "paediatric gastroenterology, hepatology and nutrition",
            "paediatric endocrinology and diabetes",
            "paediatric cardiology",
            "paediatric allergology",
            "otorhinolaryngology",
            "orthopaedics",
            "orthodontics",
            "oral and maxillofacial surgery",
            "ophthalmology",
            "occupational medicine",
            "obstetrics and gynaecology",
            "nuclear medicine",
            "neurosurgery",
            "neuroradiology",
            "neurology",
            "nephrology",
            "neonatology",
            "interventional radiology",
            "internal medicine",
            "intensive care medicine",
            "infectious disease",
            "hospice and palliative medicine",
            "health informatics",
            "geriatrics",
            "general surgery",
            "general practice",
            "gastroenterology",
            "endocrinology",
            "emergency medicine",
            "dermatology-venereology",
            "colon and rectal surgery",
            "clinical neurophysiology",
            "child and adolescent psychiatry and psychotherapy",
            "cardiothoracic surgery",
            "cardiology",
            "anaesthesiology",
            "allergy and immunology",
            "aerospace medicine",
            "adolescent medicine",
            "hospital",
            "hospitals",
            "clinic",
            "clinics",
            "laboratory",
            "laboratories",
            "medical",
            "medicals",
            "pharmacy",
            "nursing home",
            "diagnostic",
            "dispensary",
            "trauma centre",
            "diagnostics",
            "laboratories",
            "health",
            "labs",
            "lab",
            "cancer centre",
            "medicos",
            "eye care",
            "medicare centre",
            "medicare center",
            "eyecare centre",
            "eyecare center",
            "medico",
            "adrenals",
            "appendix",
            "bladder",
            "brain",
            "esophagus",
            "eyes",
            "gallbladder",
            "heart",
            "intestines",
            "kidney",
            "liver",
            "lung",
            "ovaries",
            "pancreas",
            "parathyroids",
            "pituitary",
            "prostate",
            "spleen",
            "stomach",
            "testicles",
            "thymus",
            "thyroid",
            "uterus",
            "veins",
            "neurologist",
            "physician",
            "neurosurgeon",
            "plastic surgeon",
            "general surgeon",
            "ophthalmologist",
            "cancer",
            "cardiologist",
            "orthopedics",
            "neurologist",
            "dentist",
            "orthodontist",
            "paediatricians",
            "psychiatrist",
            "urologist",
            "nephrologist",
            "gynacologist",
            "severe headache",
            "unconsciousness",
            "giddiness",
            "blackout",
            "convulsion",
            "paralysis",
            "acute confusion",
            "swelling head",
            "swelling face",
            "swelling neck",
            "blindness",
            "any eye problem",
            "loss of vision",
            "bleeding from ear",
            "bleeding from nose",
            "difficulty in swallowing",
            "stuck fish bone in throat",
            "stuck bone in throat",
            "any nose problem",
            "any ear problem",
            "bleeding from mouth",
            "accidentally swallowed object/coin",
            "vomiting",
            "swelling in mouth",
            "wound/patch in mouth",
            "unable to swallow",
            "chest pain",
            "palpitation",
            "fast heart beat",
            "slow heart beat",
            "missed heart beat",
            "swelling",
            "breathlessness",
            "asthma",
            "severe cough",
            "blood in cough",
            "pain in abdomen",
            "blood in vomitus",
            "bleeding per rectum",
            "absolute constipation",
            "abdominal swelling",
            "unable to swallow",
            "anus any problem",
            "diarrhea",
            "vomiting",
            "indigestion",
            "abdomen hernia",
            "groin hernia",
            "pain",
            "swelling",
            "bedsore",
            "swelling",
            "discoloration",
            "wound",
            "pain",
            "weakness",
            "fracture",
            "toothache",
            "gum bleeding",
            "any dental problem",
            "tooth deformity",
            "gum swelling",
            "ulcer in mouth",
            "all problems",
            "fever",
            "skin eruptions",
            "rashes",
            "suicidal tendencies",
            "acute mania",
            "excessive sweating",
            "excessive weakness",
            "insomnia (inability to sleep)",
            "abnormal body sensation",
            "abnormal body movement",
            "wound anywhere",
            "jaundice",
            "breast surgeon",
            "gastroenetrologist",
            "dr.",
            "doctor",
            "blood bank",
            "ambulance",
            "eye bank",
            "patient",
            "drug",
            "chemist",
            "wellness",
            "hearing aid",
            "physio",
            "physiotherapy",
            "physiotherapist",
            "janaushadi",
            "Medi",
            "Aushad",
            "Aushadi",
            "Infertility",
            "pharma",
            "vivante",
            "Lenskart",
            "Dog",
            "Cat",
            "Pet",
            "Veterinary",
            "Animal",
            "Vet",
            "Happy tails",
            "Pets",
            "Optics",
            "Opticals",
            "Ayurveda",
            "Ayurved",
            "Skin",
            "Netralaya",
            "Optician",
            "Eyewear",
            "Eye wear",
            "Eye Plus",
            "Imaging centre",
            "eye ",
            "opd ",
            "dr ",

    };

}
